### ISSUE TITLE
Abstract RTNS Construction

### ISSUE THREAD

**Issue by bonedaddy** [RTradeLtd/rtns#20]
# Assignee: @arku 

Currently `rtns` does a bunch of work internally when creating the system. This involves things like creating the libp2p host, creating a krab gRPC keystore wrapper.

Instead, we should provide these various interface types, such as the libp2p host, the libp2p DHT, etc.. Additionally, we should not provide a specific keystore type (krab) but instead, provide the `keystore.Keystore` interface abstraction, allowing implementers of this package to choose a desired keystore.

**Comment by arku** [comment]
@postables I would like to pick this one.
